# Minimal firmware image for solar-ctl.
#
# core-image-base already drags in packagegroup-core-basic, which pulls
# util-linux, shadow and other fat we don't want. Start from the bare
# -minimal recipe instead and add back only the essentials.
require recipes-core/images/core-image-minimal.bb

SUMMARY = "solar-ctl firmware image (musl + busybox + systemd)"
LICENSE = "MIT"

# sshd so we can bring the board up remotely. A getty on the mini-UART
# comes automatically: systemd's serial-getty generator reacts to the
# console= kernel cmdline arg (from SERIAL_CONSOLES + ENABLE_UART=1).
IMAGE_FEATURES += "ssh-server-dropbear"

# --- Bring-up access policy (DEV ONLY - rework before deployment) ----------
# UART:   empty root password + autologin root on the serial console, so a
#         UART cable alone gets you a root shell (nothing to type).
# SSH:    root-only, key-only - dropbear runs with -s (password logins
#         disabled; see dropbear.default) and only
#         /root/.ssh/authorized_keys exists (solar-rootkeys). Non-root
#         accounts have no key and no password.
# Before shipping: drop empty-root-password + serial-autologin-root, set a
# root password (or lock it), and keep key access only.
IMAGE_FEATURES += "allow-root-login empty-root-password serial-autologin-root"

# meta-raspberrypi adds 'kernel-modules' (= literally every kernel module,
# ~1800 packages) to MACHINE_EXTRA_RRECOMMENDS for every rpi machine, and
# BT firmware we don't use (no bluetooth distro feature). Drop both.
# Do NOT rely on MACHINE_EXTRA_RRECOMMENDS for WiFi firmware: the 2026-09-18
# image had linux-firmware-rpidistro-bcm43430 in that list and still omitted
# the package — install it explicitly. LICENSE_FLAGS_ACCEPTED is already set
# in kas-rpi0.yml.
MACHINE_EXTRA_RRECOMMENDS:remove = "kernel-modules bluez-firmware-rpidistro-bcm43430a1-hcd"

# brcmfmac on kernel 6.18 runtime-requests a per-vendor firmware plugin
# (brcmfmac-cyw for the 43430) via request_module(); the module name is
# built at runtime (fwvid.c), so modpost records no softdep and the
# package is never pulled in automatically - without it the modprobe
# fails and no wlan0 appears. Install it explicitly.
IMAGE_INSTALL:append = " \
    kernel-module-brcmfmac \
    kernel-module-brcmfmac-cyw \
    linux-firmware-rpidistro-bcm43430 \
    wireless-regdb \
    wpa-supplicant \
    solar-wifi \
    solar-rootkeys \
"

# Bring-up/debug tooling for the RS485 Modbus bus (Deye inverter).
# USB serial driver packages cover the chips commonly used by USB-RS485
# adapters; drop whichever ones you don't need later. Remove mbpoll (GPL-3)
# from production images if its license doesn't suit distribution.
# rs485ctl toggles the kernel RS485 RTS direction control on ttyAMA0
# once the native transceiver is wired up (dtoverlay=solar-rs485).
IMAGE_INSTALL:append = " \
    mbpoll \
    rs485ctl \
    kernel-module-usbserial \
    kernel-module-ftdi-sio \
    kernel-module-cp210x \
    kernel-module-ch341 \
    kernel-module-pl2303 \
    kernel-module-cdc-acm \
"

# NV3007 2.79" TFT (dtoverlay=nv3007): generic panel-mipi-dbi driver +
# SPI host + GPIO backlight. Remaining deps (drm-mipi-dbi, kms helpers,
# fbdev emulation) come via the kernel module packages' own RDEPENDS.
# NOTE: the panel only comes up once the NV3007 init sequence is present
# as /lib/firmware/panel-mipi-dbi-spi.bin (vendor init code - see README).
IMAGE_INSTALL:append = " \
    kernel-module-panel-mipi-dbi \
    kernel-module-spi-bcm2835 \
    kernel-module-gpio-backlight \
"

# Placeholder for the inverter controller app once it lands:
# IMAGE_INSTALL:append = " inv-ctl"

# --- A/B OTA milestone (doc swupdate-ota.md §5, §10 step 4) ---------------
# Layout: p1 vfat (GPU fw + U-Boot + per-slot kernel) + p2/p3 squashfs-xz
# root slots + p4 ext4 /data. The wks is found via WKS_SEARCH_PATH
# (files/wic/ of this layer) and overrides rpi-base.inc's WKS_FILE ?=.
WKS_FILE = "solar-ctl-ab.wks"

# Kickstart: per-slot kernel copy on p1. The top-level uImage (from
# RPI_EXTRA_IMAGE_BOOT_FILES) stays as the fallback the boot script uses
# while slot-b/ is empty.
IMAGE_BOOT_FILES:append = " uImage;slot-a/uImage"

# /etc as overlay: the preinit generated by the overlayfs-etc class mounts
# p4 at /data, creates /data/overlay-etc/{upper,work} there and overlays
# /etc (upper shared by both slots - the §9 hazard). CREATE_MOUNT_DIRS=0 is
# MANDATORY: the =1 path does `mount -o remount,rw /`, which can never work
# on a squashfs root. With =0 preinit does not mkdir the mount point either,
# so the RO rootfs must carry /data itself (do_rootfs:append below; /proc,
# /sys, /run, /var/run come from base-files - spot-checked in the built
# rootfs).
IMAGE_FEATURES += "overlayfs-etc"
OVERLAYFS_ETC_MOUNT_POINT = "/data"
OVERLAYFS_ETC_FSTYPE = "ext4"
OVERLAYFS_ETC_DEVICE = "/dev/mmcblk0p4"
OVERLAYFS_ETC_CREATE_MOUNT_DIRS = "0"

# /etc overlay needs overlay.ko in the image (test-0 probe: MISSING on the
# smoke image - same class of gotcha as brcmfmac-cyw: no RRECOMMENDS chain
# ever pulls it in). squashfs is deliberately NOT here: it is built into the
# kernel (solar-ctl-slim.cfg) because there is no initramfs to load it
# before mounting root, so the kernel-module-squashfs package no longer
# exists at all.
# u-boot-env ships /etc/fw_env.config (-> /boot/uboot.env); libubootenv-bin
# is the wrynose fw_printenv/fw_setenv, so a slot switch is
#   mount -o remount,rw /boot; fw_setenv slot b; mount -o remount,ro /boot
IMAGE_INSTALL:append = " \
    kernel-module-overlay \
    u-boot-env \
    libubootenv-bin \
"

# /data must exist on the RO rootfs for the overlayfs-etc preinit (it does
# not create the mount point with OVERLAYFS_ETC_CREATE_MOUNT_DIRS=0).
# NB: do_rootfs itself is a "fakeroot python" task in image.bbclass, so a
# plain do_rootfs:append() with shell in it does not parse - use the
# postprocess hook instead (it runs inside do_rootfs, still under fakeroot).
ROOTFS_POSTPROCESS_COMMAND:append = " solar_ab_create_data_dir;"
solar_ab_create_data_dir() {
    mkdir -p ${IMAGE_ROOTFS}/data
}

COMPATIBLE_MACHINE = "^raspberrypi"
